package br.java.intermediario.enums.enums;

public enum TemporadaHIMYM {

        TEMPORADA_UM, TEMPORADA_DOIS, TEMPORADA_TRES, TEMPORADA_QUATRO, TEMPORADA_CINCO, TEMPORADA_SEIS, TEMPORADA_SETE, TEMPORADA_OITO, TEMPORADA_NOVE;

}
